version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: po_con
    environment:
      POSTGRES_USER: telay
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: uog
    ports:
      - "5431:5432"

  hasura:
    image: hasura/graphql-engine:latest
    container_name: hasura_container
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://telay:123456@postgres:5432/uog
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: Telay5870@
    ports:
      - "8083:8080"
    restart: always
